// Имитация API-запроса
export const fetchDataFromApi = async () => {
  // В реальном приложении здесь был бы fetch-запрос к серверу
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          name: 'Процессор Intel Core i9',
          performance: 95,
          powerConsumption: 125,
          temperature: 75,
          price: 48000,
          reliability: 92,
          marketShare: 45,
          customerRating: 4.8,
        },
        {
          name: 'Процессор AMD Ryzen 9',
          performance: 92,
          powerConsumption: 105,
          temperature: 70,
          price: 42000,
          reliability: 90,
          marketShare: 38,
          customerRating: 4.7,
        },
        {
          name: 'Процессор Intel Xeon',
          performance: 88,
          powerConsumption: 150,
          temperature: 80,
          price: 65000,
          reliability: 95,
          marketShare: 60,
          customerRating: 4.5,
        },
        {
          name: 'Процессор AMD EPYC',
          performance: 96,
          powerConsumption: 180,
          temperature: 85,
          price: 72000,
          reliability: 93,
          marketShare: 30,
          customerRating: 4.6,
        },
        {
          name: 'Процессор ARM Cortex',
          performance: 75,
          powerConsumption: 45,
          temperature: 55,
          price: 25000,
          reliability: 88,
          marketShare: 15,
          customerRating: 4.2,
        },
        {
          name: 'Процессор RISC-V',
          performance: 70,
          powerConsumption: 40,
          temperature: 50,
          price: 20000,
          reliability: 85,
          marketShare: 5,
          customerRating: 4.0,
        },
        {
          name: 'Процессор IBM Power',
          performance: 85,
          powerConsumption: 160,
          temperature: 82,
          price: 80000,
          reliability: 97,
          marketShare: 8,
          customerRating: 4.4,
        },
        {
          name: 'Процессор Эльбрус',
          performance: 65,
          powerConsumption: 110,
          temperature: 72,
          price: 35000,
          reliability: 80,
          marketShare: 2,
          customerRating: 3.8,
        },
        {
          name: 'Процессор Байкал',
          performance: 60,
          powerConsumption: 95,
          temperature: 68,
          price: 30000,
          reliability: 78,
          marketShare: 1,
          customerRating: 3.7,
        },
        {
          name: 'Процессор Мультикор',
          performance: 82,
          powerConsumption: 120,
          temperature: 76,
          price: 38000,
          reliability: 86,
          marketShare: 3,
          customerRating: 4.1,
        },
      ]);
    }, 1000); // Имитация задержки сети
  });
};
